apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app.kubernetes.io/name: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 32000